### PR TITLE
Simplified dependency using nette/utils only

### PR DESCRIPTION
**Pull request by stekycz**
It is impossible to use only some nette packages in project using also this library. So it was impossible to remove nette/database as dependency from project. In the end why use nette/database using this specific library ;-)

### CODE REVIEW

**Comment by fprochazka** [comment]
This is not a solution.

**Comment by stekycz** [comment]
I can see. However then there should be created specific branches for older nette versions. What do you suggest?

**Comment by fprochazka** [comment]
Yes, exactly :) I have to create release branch for nette-2.1 and make master 2.2-only

**Comment by stekycz** [comment]
Is it a problem? :-) I think it is the same as in [Kdyby/Money](https://github.com/Kdyby/Money/blob/master/composer.json)

**Comment by fprochazka** [comment]
It's not a problem, it just takes time :)

**Comment by fprochazka** [comment]
Solved, thank you.

**Pull request closed without merging**
